# Generated by Django 3.1.7 on 2021-03-11 00:35

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter the breed of cat', max_length=100, validators=[django.core.validators.MinLengthValidator(2, '\n        Breed name must have more than 2 characters\n        ')])),
            ],
        ),
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pet_name', models.CharField(help_text='Enter the name of your pet', max_length=200, validators=[django.core.validators.MinLengthValidator(1, '\n        Pet name must have 1 or more characters\n        ')])),
                ('weight', models.FloatField()),
                ('foods', models.CharField(max_length=300)),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cats.breed')),
            ],
        ),
    ]
